spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123456
user:
  name: ss
  age: 18
logging:
  level:
    com.alibaba.nacos.client.config.impl.ClientWorker: error
server:
  port: 8070